import yeticave from '../../assets/projects/yeticave.webp';
import createX from '../../assets/projects/create-x-construction.webp';
import nikeEcommerce from '../../assets/projects/nike-ecommerce.webp';
import personalDiary from '../../assets/projects/personal-diary.webp';
import topApp from '../../assets/projects/05-big.webp';
import dictionary from '../../assets/projects/dictionary.webp';
import blog from '../../assets/projects/blogWebp.webp';
import ratingus from '../../assets/projects/ratingus.webp';
import waterdel from '../../assets/projects/waterdel.webp';
import bringitup from '../../assets/projects/bringitup.webp';

export const projects = [
  {
    id: 1,
    title: 'projects.project1.title',
    skills: 'JavaScript, PHP, HTML, CSS',
    img: yeticave,
    slogan: 'projects.project1.slogan',
    gitHubLink: 'https://github.com/ministrov/yetycave-php',
    overview: 'projects.project1.overview',
    isProduction: false,
    year: 2023,
    role: 'intern Front-end Developer',
    infoTitle: 'projects.project1.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 2,
    title: 'projects.project2.title',
    skills: 'JavaScript, HTML5, CSS3',
    img: createX,
    demoLink: 'https://create-x-construction.vercel.app/',
    slogan: 'projects.project2.slogan',
    overview: 'projects.project2.overview',
    isProduction: true,
    year: 2021,
    role: 'intern Front-end Developer',
    infoTitle: 'projects.project2.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 3,
    title: 'projects.project3.title',
    skills: 'React, Tailwind CSS',
    img: nikeEcommerce,
    gitHubLink: 'https://github.com/ministrov/nike-react-tailwilnd',
    slogan: 'projects.project3.slogan',
    overview: 'projects.project3.overview',
    isProduction: false,
    demoLink: 'https://nike-react-tailwilnd.vercel.app/',
    year: 2022,
    role: 'Front-end Developer',
    infoTitle: 'projects.project3.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 4,
    title: 'projects.project4.title',
    skills: 'React, React-Router, classnames',
    img: personalDiary,
    slogan: 'projects.project4.slogan',
    gitHubLink: 'https://github.com/ministrov/react-journal',
    overview: 'projects.project4.overview',
    isProduction: false,
    year: 2022,
    role: 'Front-end Developer',
    infoTitle: 'projects.project4.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 5,
    title: 'projects.project5.title',
    skills: 'Next, TypeScript, React, Framer Motion, React Hook Form',
    img: topApp,
    slogan: 'projects.project5.slogan',
    gitHubLink: 'https://github.com/ministrov/top-app-next-ts',
    overview: 'projects.project5.overview',
    isProduction: true,
    year: 2025,
    role: 'Front-end Developer',
    infoTitle: 'projects.project5.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 6,
    title: 'projects.project6.title',
    skills: 'Next, TypeScript, React, Zustand, Yup, Formik, Framer Motion',
    img: ratingus,
    slogan: 'projects.project6.slogan',
    gitHubLink: 'https://github.com/PurpleSchoolPractice/ratingus-site',
    demoLink: 'https://ratingus.ru/',
    overview: 'projects.project6.overview',
    isProduction: true,
    year: 2024,
    role: 'Front-end Developer',
    infoTitle: 'projects.project6.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 7,
    title: 'projects.project7.title',
    skills: 'Next, TypeScript, React, Framer Motion',
    img: blog,
    slogan: 'projects.project7.slogan',
    gitHubLink: 'https://github.com/ministrov/personal-blog-next-ts',
    overview: 'projects.project7.overview',
    isProduction: false,
    year: 2025,
    role: 'Front-end Developer',
    infoTitle: 'projects.project7.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 8,
    title: 'projects.project8.title',
    skills: 'JavaScript, HTML, CSS',
    img: dictionary,
    slogan: 'projects.project8.slogan',
    overview: 'projects.project8.overview',
    isProduction: false,
    year: 2021,
    role: 'intern Front-end Developer',
    infoTitle: 'projects.project8.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 9,
    title: 'projects.project9.title',
    skills: 'JavaScript, HTML, CSS',
    img: waterdel,
    slogan: 'projects.project9.slogan',
    overview: 'projects.project9.overview',
    demoLink: 'https://waterdel.ru/',
    isProduction: true,
    year: 2022,
    role: 'intern Front-end Developer',
    infoTitle: 'projects.project9.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
  {
    id: 10,
    title: 'projects.project10.title',
    skills: 'JavaScript, HTML, CSS, OOP, SOLID',
    img: bringitup,
    slogan: 'projects.project10.slogan',
    overview: 'projects.project10.overview',
    isProduction: false,
    year: 2024,
    role: 'Front-end Developer',
    infoTitle: 'projects.project10.infoTitle',
    yearText: 'Year',
    roleText: 'Role',
  },
];
