import createX from '../../assets/projects/create-x-construction.webp';
import nikeEcommerce from '../../assets/projects/nike-ecommerce.webp';
import topApp from '../../assets/projects/topApp.webp';
import blog from '../../assets/projects/blogWebp.webp';
import ratingus from '../../assets/projects/ratingus.webp';
import waterdel from '../../assets/projects/waterdel.webp';
import shoppe from '../../assets/projects/shoppe.webp';

export const projects = [
  {
    id: 1,
    title: 'projects.project9.title',
    skills: 'JavaScript, HTML, CSS',
    img: waterdel,
    slogan: 'projects.project9.slogan',
    overview: 'projects.project9.overview',
    gitHubLink: 'https://github.com/ministrov/waterdel-newest',
    demoLink: 'https://waterdel.store/',
    isProduction: true,
    year: 2026,
    role: 'Senior Frontend Developer',
    infoTitle: 'projects.project9.infoTitle',
    toolsTitle: 'projects.project9.toolsTitle',
    yearText: 'projects.project9.yearText',
    roleText: 'projects.project9.roleText',
    isReversed: false,
  },
  {
    id: 2,
    title: 'projects.project3.title',
    skills: 'React, Tailwind CSS',
    img: nikeEcommerce,
    gitHubLink: 'https://github.com/ministrov/nike-react-tailwilnd',
    slogan: 'projects.project3.slogan',
    overview: 'projects.project3.overview',
    isProduction: false,
    demoLink:
      'https://nike-react-tailwilnd-hpwsvyjlg-ministrovs-projects.vercel.app',
    year: 2022,
    role: 'Frontend Developer',
    infoTitle: 'projects.project3.infoTitle',
    toolsTitle: 'projects.project3.toolsTitle',
    yearText: 'projects.project3.yearText',
    roleText: 'projects.project3.roleText',
    isReversed: true,
  },
  {
    id: 3,
    title: 'projects.project5.title',
    skills: 'Next, TypeScript, React, Framer Motion, React Hook Form',
    img: topApp,
    slogan: 'projects.project5.slogan',
    gitHubLink: 'https://github.com/ministrov/top-app-next-ts',
    overview: 'projects.project5.overview',
    isProduction: true,
    year: 2025,
    role: 'Frontend Developer',
    infoTitle: 'projects.project5.infoTitle',
    toolsTitle: 'projects.project5.toolsTitle',
    yearText: 'projects.project5.yearText',
    roleText: 'projects.project5.roleText',
    isReversed: false,
  },
  {
    id: 4,
    title: 'projects.project6.title',
    skills: 'Next, TypeScript, React, Zustand, Yup, Formik, Framer Motion',
    img: ratingus,
    slogan: 'projects.project6.slogan',
    overview: 'projects.project6.overview',
    isProduction: true,
    year: 2024,
    role: 'Frontend Developer',
    infoTitle: 'projects.project6.infoTitle',
    toolsTitle: 'projects.project6.toolsTitle',
    yearText: 'projects.project6.yearText',
    roleText: 'projects.project6.roleText',
    isReversed: true,
  },
  {
    id: 5,
    title: 'projects.project7.title',
    skills: 'Next, TypeScript, React, Framer Motion',
    img: blog,
    slogan: 'projects.project7.slogan',
    gitHubLink: 'https://github.com/ministrov/personal-blog-next-ts',
    overview: 'projects.project7.overview',
    isProduction: false,
    year: 2025,
    role: 'Frontend Developer',
    infoTitle: 'projects.project7.infoTitle',
    toolsTitle: 'projects.project7.toolsTitle',
    yearText: 'projects.project7.yearText',
    roleText: 'projects.project7.roleText',
    isReversed: false,
  },
  {
    id: 6,
    title: 'projects.project2.title',
    skills: 'JavaScript, HTML5, CSS3',
    img: createX,
    demoLink: 'https://create-x-construction.vercel.app/',
    slogan: 'projects.project2.slogan',
    overview: 'projects.project2.overview',
    isProduction: true,
    year: 2021,
    role: 'intern Frontend Developer',
    infoTitle: 'projects.project2.infoTitle',
    toolsTitle: 'projects.project2.toolsTitle',
    yearText: 'projects.project2.yearText',
    roleText: 'projects.project2.roleText',
    isReversed: true,
  },
  {
    id: 7,
    title: 'projects.project10.title',
    skills: 'Next, TypeScript, React, Framer Motion',
    img: shoppe,
    gitHubLink: 'https://github.com/ministrov/shoppe-ecommerce-next',
    slogan: 'projects.project10.slogan',
    overview: 'projects.project10.overview',
    isProduction: false,
    year: 2025,
    role: 'Frontend Developer',
    infoTitle: 'projects.project10.infoTitle',
    toolsTitle: 'projects.project10.toolsTitle',
    yearText: 'projects.project10.toolsTitle',
    roleText: 'projects.project10.roleText',
    isReversed: false,
  },
];
